### ISSUE TITLE
OpenSSL certificate verify failed

### ISSUE THREAD

**Issue by thoresuenert** [beyondcode/expose#400]
We cannot use expose because of the following error:

```
herd share
Could not connect to the server.
Connection to tls://sharedwithexpose.com:443 failed during TLS handshake: SSL operation failed with code 1. OpenSSL Error messages: error:0A000086:SSL routines::certificate verify failed
```

```
expose
Could not connect to the server.
Connection to tls://sharedwithexpose.com:443 failed during TLS handshake: SSL operation failed with code 1. OpenSSL Error messages: error:0A000086:SSL routines::certificate verify failed
```
We cannot gather more info by using -vvv, the command quits with the same output.
Anything we can provide to debug this problem?

**Comment by mpociot** [comment]
We deployed a new EU-1 server, which is now available and introduced this downtime 👍

**Comment by thoresuenert** [comment]
Problem still exists for me.
Can there be caching problems involved?

**Comment by michaelklopf** [comment]
@mpociot 

How to solve the problem, the service is not working, even with using Pro.

**Comment by mpociot** [comment]
@michaelklopf are you also using the fish shell?

Right now, Herd only supports Bash and ZSH, in which case those files get automatically modified during the onboarding of Herd.
But you're right, I'll add this to the Herd documentation 👍
